all:
	g++ quicksort_verbose.cpp -o quicksort_verbose.out
	g++ quicksort_timed.cpp -o quicksort_timed.out
	g++ quicksort_stats.cpp -o quicksort_stats.out

	g++ mergesort_verbose.cpp -o mergesort_verbose.out
	g++ mergesort_timed.cpp -o mergesort_timed.out
	g++ mergesort_stats.cpp -o mergesort_stats.out



clean:
	rm *.out