all:
	g++ Enumeration.cpp -o Enumeration.out
	g++ EnumerationTimed.cpp -o EnumerationTimed.out
	g++ SubSetEnumerationTimed.cpp -o SubSetEnumerationTimed.out
	g++ NTupleEnumerationTimed.cpp -o NTupleEnumerationTimed.out

clean:
	rm *.out